[[pages]]
path = "./example_app/Introduction.py"
name = "Introduction"
icon = "📄"

[[pages]]
name = "Synonymous mutations in COSMIC v98"
icon = "👤"
is_section = true

[[pages]]
path = "./example_app/mutation_selection_by_chroms.py"
name = "By chromosomes"
icon = "🧬"

[[pages]]
path = "./example_app/mutation_selection_by_genes.py"
name = "By genes"
icon = "🧬"

[[pages]]
path = "./example_app/mutation_selection_by_recurrents.py"
name = "By sample counts"
icon = "🧬"

[[pages]]
name = "Cancer driver synonymous mutation predictors"
icon = "🗃️"
is_section = true

[[pages]]
name = 'Training data'
path = "./example_app/trainingdata_5methods.py"
icon = "🧾"
url_path = 'trainingdata'

[[pages]]
path = "./example_app/predictions_5methods.py"
name = "Predictions"
icon = "🧾"
url_path = "predictions"
